### ISSUE TITLE
Add build for osx-arm64?

### ISSUE THREAD

**Issue by scottyhq** [conda-forge/ciso-feedstock#28]
### Comment:

I'm not familiar with the build process for osx-arm64 but just wanted to link to this issue for supporting multi-architecture pangeo docker images:
https://github.com/pangeo-data/pangeo-docker-images/issues/396#issuecomment-2148329950

**Comment by ocefpaf** [comment]
I added https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6066 to start the process but I'm curious if people are really using ciso or if that is just a left over in the image package list.

I am the maintainer of ciso BTW and I have to confess I'm keeping it alive just b/c I did not try [python-stratify](https://github.com/SciTools/python-stratify) yet. Also, many packages that are target for specific models, like mit gcm, probably have that functionality already.

**Comment by ocefpaf** [comment]
Done in https://github.com/conda-forge/ciso-feedstock/pull/30
